var MENU_SLIDER = '<div id="sidebar-wrapper">'
      +'<ul>'
          +'<li class="calculadora txt-blue" style="text-align: center;font-size:12px; background:#fcf59d;">NIÑOS</li>'
          +'<li class="calculadora"><a href="#" onClick="cambiarPagina(\'ninos_drogas.html?op=1\');">Nombre comercial</a></li>'
          +'<li class="calculadora"><a href="#" onClick="cambiarPagina(\'ninos_drogas.html?op=2\');">Droga / Principio activo</a></li>'
          +'<li class="algoritmo txt-green" style="text-align: center;font-size:12px; background:#fcf59d;">ADULTOS</li>'
          +'<li class="algoritmo"><a href="#" onClick="cambiarPagina(\'adultos_drogas.html?op=1\');">Nombre comercial</a></li>'
          +'<li class="algoritmo"><a href="#" onClick="cambiarPagina(\'adultos_drogas.html?op=2\');">Droga / Principio activo</a></li>'
          +'<li style="text-align: center;font-size:12px; background:#fcf59d;">OTROS</li>'
          +'<li><a onClick="cambiarCalculadora(\'situaciones.html\');">Situaciones de uso</a></li>'
          +'<li><a onClick="cambiarCalculadora(\'autores.html\');">Autores</a></li>'
          +'<li><a onClick="cambiarCalculadora(\'bibliografia.html\');">Bibliografía</a></li>'
          +'<li><a onClick="cambiarCalculadora(\'sugerencias.html\');">Sugerencias y comentarios</a></li>'
          +'<li><a onClick="cambiarCalculadora(\'terminos.html\');">Términos y condiciones</a></li>'
          +'<li><a onClick="cambiarCalculadora(\'privacidad.html\');">Política de privacidad</a></li>'
          +'<li><a onClick="cambiarCalculadora(\'copyright.html\');">Derecho de autor</a></li>'
      +'</ul>'
    +'</div>';
document.write(MENU_SLIDER);
